trans_base_homepage:
    pattern:  /journal
    defaults: { _controller: TransBaseBundle:Trans:journal }

trans_car_journal:
    pattern: /car_journal
    defaults: { _controller: TransBaseBundle:Car:journal}

trans_add_car:
    pattern: /add_car
    defaults: { _controller: TransBaseBundle:Car:add_car}
    
trans_add_car_base:
    pattern: /add_car_base
    defaults: {_controller: TransBaseBundle:Car:add_car_base}
    
trans_edit_car:
    pattern: /edit_car/{car_id}
    defaults: {_controller: TransBaseBundle:Car:edit_car }
  

trans_edit_car_base:
    pattern: /edit_car_base/{car_id}
    defaults: {_controller: TransBaseBundle:Car:edit_car_base}
 
trans_delete_car:
    pattern: /delete_car/{car_id}
    defaults: {_controller: TransBaseBundle:Car:delete_car}
  
trans_add_act:
    pattern: /add_act
    defaults: { _controller: TransBaseBundle:Trans:add_act}
    
trans_edit_act:
    pattern: /{_locale}/edit_act/{act_id}
    defaults: { _controller: TransBaseBundle:Trans:edit_act, _locale: en}
    requirements:
        _locale: en|fr|ru
    
trans_delete_act:
    pattern: /delete_act/{act_id}
    defaults: { _controller: TransBaseBundle:Trans:delete_act}
