parameters:
#    trans_base.example.class: Trans\BaseBundle\Example

services:
#    trans_base.example:
#        class: %trans_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
